apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: node-js-app-cpu
spec:
  maxReplicas: 15
  minReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-js-app-deploy
  targetCPUUtilizationPercentage: 50

