apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: node-js-app-hpa-memory
spec:
  maxReplicas: 15
  minReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-js-app-deploy
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 60

